edition = "2021"
max_width = 100                    # Adjust line wrapping
use_small_heuristics = "Max"
reorder_imports = true             # Sort imports
reorder_modules = true             # Sort modules
wrap_comments = true               # Wrap long comments
normalize_doc_attributes = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
